# Generated by Django 2.2.5 on 2019-09-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_example', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computers',
            options={'verbose_name': 'Computer', 'verbose_name_plural': 'Computers'},
        ),
        migrations.AddField(
            model_name='computers',
            name='comp_link',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
