# Generated by Django 2.2.5 on 2019-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_example', '0002_auto_20190907_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='comp_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computers',
            name='display_type',
            field=models.TextField(default='retina', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computers',
            name='price_currency',
            field=models.IntegerField(choices=[(1, '₽'), (2, '$'), (3, '¥')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computers',
            name='processor_type',
            field=models.TextField(default='Core i9', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computers',
            name='ram_type',
            field=models.TextField(default='8 DDR3', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computers',
            name='ssd_volume',
            field=models.TextField(default='250GB', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computers',
            name='comp_link',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='computers',
            name='picture_link',
            field=models.TextField(max_length=150),
        ),
    ]
