# Generated by Django 2.2.5 on 2019-09-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_example', '0003_auto_20190908_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computers',
            name='price_currency',
        ),
    ]
