# Generated by Django 2.2.5 on 2019-10-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_example', '0005_computers_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='comp_link',
            field=models.ImageField(upload_to=''),
        ),
    ]
